---
- name: setup default backend
  hosts: backend
  become: yes

  tasks:
    - name: install nginx
      package:
        name: nginx
        state: present
        update_cache: true

    - name: start nginx
      systemd:
        name: nginx
        state: restarted
        enabled: yes

- name: setup haproxy
  hosts: proxy 
  become: yes

  tasks:
    - name: config ip forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes
        state: present
        reload: no

    - name: config non-local ip binding
      sysctl:
        name: net.ipv4.ip_nonlocal_bind
        value: '1'
        sysctl_set: yes
        state: present
        reload: yes

    - name: install haproxy
      package:
        name: haproxy
        state: present
        update_cache: true
    
    - name: append configurations
      template:
        src: haproxy-cfg.j2
        dest: /etc/haproxy/haproxy.cfg

    - name: start haproxy
      systemd:
        name: haproxy
        state: restarted

- name: setup keepalived
  hosts: proxy 
  become: yes

  tasks:
    - name: install keepalived
      package:
        name: keepalived
        state: present
        update_cache: true

    - name: configurations - master
      vars:
        ip_state: MASTER
      template:
        src: keepalived-conf.j2
        dest: /etc/keepalived/keepalived.conf
      when: "'proxy-01' in inventory_hostname"

    - name: configurations - backup
      vars:
        ip_state: BACKUP
      template:
        src: keepalived-conf.j2
        dest: /etc/keepalived/keepalived.conf
      when: "'proxy-02' in inventory_hostname"

    - name: start keepalived
      systemd:
        name: keepalived
        state: restarted
        enabled: yes
