---
- name: setup default backend
  hosts: backend
  become: yes

  tasks:
    - name: install nginx
      package:
        name: nginx
        state: present
        update_cache: true

    - name: start nginx
      systemd:
        name: nginx
        state: restarted
        enabled: yes

- name: setup haproxy
  hosts: proxy 
  become: yes

  tasks:
    - name: config ip forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes
        state: present
        reload: no

    - name: config non-local ip binding
      sysctl:
        name: net.ipv4.ip_nonlocal_bind
        value: '1'
        sysctl_set: yes
        state: present
        reload: yes

    - name: install haproxy
      package:
        name: haproxy
        state: present
        update_cache: true
    
    - name: append configurations
      blockinfile:
        path: /etc/haproxy/haproxy.cfg
        block: |
          frontend web-frontend
            bind *:80
            mode http
            default_backend web-backend
        
          backend web-backend
            balance roundrobin
            server web1 {{ hostvars['web-01'].ansible_host }}:80 check
            server web2 {{ hostvars['web-02'].ansible_host }}:80 check

          listen stats
            bind {{ haproxy_stats_bind }}
            mode http
            stats enable
            stats hide-version
            stats realm Haproxy\ Statistics
            stats uri /
            stats auth {{ haproxy_stats_creds }}

    - name: start haproxy
      systemd:
        name: haproxy
        state: restarted

- name: setup keepalived
  hosts: proxy 
  become: yes

  tasks:
    - name: install keepalived
      package:
        name: keepalived
        state: present
        update_cache: true

    - name: configurations - master
      vars:
        ip_state: MASTER
      template:
        src: keepalived-conf.j2
        dest: /etc/keepalived/keepalived.conf
      when: "'proxy-01' in inventory_hostname"

    - name: configurations - backup
      vars:
        ip_state: BACKUP
      template:
        src: keepalived-conf.j2
        dest: /etc/keepalived/keepalived.conf
      when: "'proxy-02' in inventory_hostname"

    - name: start keepalived
      systemd:
        name: keepalived
        state: restarted
        enabled: yes
